"""Phase-14 Quick96 Torch training/persistence contract.

The frozen fixture was generated by
``tests/parity/generate_quick96_tf_reference.py`` from official DFL commit
14cc9d4e5ffc062856a739c8e64707654780774e.  It is synthetic and contains no
user media or pretrained resource bytes.
"""

import json
import hashlib
import os
import pickle
import shutil
import subprocess
from pathlib import Path

import numpy as np
import pytest
import torch

from core.leras import nn
from core.leras.checkpoint import CheckpointLoadError
from core.leras.device import Devices
from models.Model_Quick96 import Model as Quick96Model
from tests.parity.generate_quick96_tf_reference import (
    OfficialSourceAuthenticationError, _stable_number,
    authenticate_official_root, synthetic_value)
from tests.smoke.Model_SAEHDTest.Model import make_training_dirs


REFERENCE = (Path(__file__).parents[1] / "parity" / "fixtures"
             / "quick96_tf_reference.npz")

# Frozen FP32 cross-framework contract. These are absolute tolerances because
# every fixture field has a fixed bounded synthetic scale. They leave useful
# headroom for different FP32 convolution/reduction accumulation orders while
# remaining tight enough to reject layout, activation, masking, or reduction
# changes: encoder has four strided convolutions; inter is a small-valued
# dense/upscale result; decoder and blur outputs are bounded near [0, 1]; the
# two loss vectors include large spatial reductions. Controlled RMSprop is a
# scalar elementwise contract and is required to remain exact below.
PARITY_FIELDS = {
    "encoder_src": ((2, 18432), np.float32, 3e-5),
    "inter_src": ((2, 6, 6, 128), np.float32, 2e-7),
    "decoder_src_face": ((2, 96, 96, 3), np.float32, 2e-6),
    "decoder_src_mask": ((2, 96, 96, 1), np.float32, 2e-6),
    "decoder_dst_face": ((2, 96, 96, 3), np.float32, 2e-6),
    "decoder_dst_mask": ((2, 96, 96, 1), np.float32, 2e-6),
    "ae_view_src": ((2, 96, 96, 3), np.float32, 2e-6),
    "ae_view_dst": ((2, 96, 96, 3), np.float32, 2e-6),
    "ae_view_dst_mask": ((2, 96, 96, 1), np.float32, 2e-6),
    "ae_view_swap": ((2, 96, 96, 3), np.float32, 2e-6),
    "ae_view_swap_mask": ((2, 96, 96, 1), np.float32, 2e-6),
    "ae_merge_face": ((2, 96, 96, 3), np.float32, 2e-6),
    "ae_merge_src_mask": ((2, 96, 96, 1), np.float32, 2e-6),
    "ae_merge_dst_mask": ((2, 96, 96, 1), np.float32, 2e-6),
    "src_mask_blur": ((2, 96, 96, 1), np.float32, 1e-6),
    "dst_mask_blur": ((2, 96, 96, 1), np.float32, 1e-6),
    "src_loss": ((2,), np.float32, 2e-5),
    "dst_loss": ((2,), np.float32, 1e-5),
}


def _assert_parity_field(name, actual, expected):
    shape, dtype, atol = PARITY_FIELDS[name]
    actual = np.asarray(actual)
    expected = np.asarray(expected)
    assert actual.shape == shape
    assert expected.shape == shape
    assert actual.dtype == dtype
    assert expected.dtype == dtype
    np.testing.assert_allclose(actual, expected, rtol=0.0, atol=atol,
                               err_msg=name)


def _reference():
    fixture = np.load(REFERENCE)
    return fixture, json.loads(str(fixture["metadata"]))


def _components(device_config=None):
    nn.initialize(device_config or nn.DeviceConfig.CPU(), data_format="NHWC")
    archi = nn.DeepFakeArchi(96, opts="ud")
    encoder = archi.Encoder(3, 64, name="encoder")
    encoder_out_ch = encoder.get_out_ch() * encoder.get_out_res(96) ** 2
    inter = archi.Inter(encoder_out_ch, 128, 128, name="inter")
    decoder_src = archi.Decoder(inter.get_out_ch(), 64, 16,
                                name="decoder_src")
    decoder_dst = archi.Decoder(inter.get_out_ch(), 64, 16,
                                name="decoder_dst")
    return encoder, inter, decoder_src, decoder_dst


def _load_synthetic_components(components, metadata, root):
    root = Path(root)
    for component in components:
        payload = {}
        for item in metadata["components"][component.name]:
            full_name = f"{component.name}/{item['key']}"
            payload[item["key"]] = synthetic_value(
                full_name, tuple(item["shape"]))
        path = root / f"{component.name}.npy"
        path.write_bytes(pickle.dumps(payload, 4))
        assert component.load_weights(path)


def _np(tensor):
    return tensor.detach().cpu().numpy()


def _tensor_digest(tensor):
    value = tensor.detach().cpu().contiguous().numpy()
    return hashlib.sha256(value.tobytes()).hexdigest()


def _probes(values):
    result = []
    for value in values:
        flat = _np(value).reshape(-1)
        indexes = sorted({0, len(flat) // 2, len(flat) - 1})
        result.append([float(flat[i]) for i in indexes])
    return np.asarray(result, dtype=np.float64)


def _official_probes(saveable, values, identities):
    converted = [
        saveable.convert_weight_to_official(_np(value), identity)
        for value, identity in zip(values, identities)]
    result = []
    for value in converted:
        flat = np.asarray(value).reshape(-1)
        indexes = sorted({0, len(flat) // 2, len(flat) - 1})
        result.append([float(flat[i]) for i in indexes])
    return np.asarray(result, dtype=np.float64)


def _make_model(root, *, cpu_only=True, force_gpu_idxs=None,
                pretrained_model_path=None, debug=True):
    root = Path(root)
    root.mkdir(parents=True, exist_ok=True)
    if not (root / "src" / "faceset.pak").exists():
        make_training_dirs(root)
    return Quick96Model(
        is_training=True,
        saved_models_path=root,
        training_data_src_path=root / "src",
        training_data_dst_path=root / "dst",
        pretraining_data_path=None,
        pretrained_model_path=pretrained_model_path,
        force_model_class_name="test_Quick96",
        cpu_only=cpu_only,
        force_gpu_idxs=force_gpu_idxs,
        debug=debug,
        no_preview=True,
    )


def _synthetic_batch(model, batch=None, identical=False):
    n = model.get_batch_size() if batch is None else batch
    if model.model_data_format == "NHWC":
        image_shape, mask_shape = (n, 96, 96, 3), (n, 96, 96, 1)
    else:
        image_shape, mask_shape = (n, 3, 96, 96), (n, 1, 96, 96)
    rng = np.random.default_rng(1400)
    if identical:
        image = rng.random(image_shape[1:], dtype=np.float32)
        mask = rng.random(mask_shape[1:], dtype=np.float32)
        images = [np.repeat(image[None], n, axis=0) for _ in range(4)]
        masks = [np.repeat(mask[None], n, axis=0) for _ in range(2)]
    else:
        images = [rng.random(image_shape, dtype=np.float32) for _ in range(4)]
        masks = [rng.random(mask_shape, dtype=np.float32) for _ in range(2)]
    return (images[0], images[1], masks[0],
            images[2], images[3], masks[1])


def _controlled_dropout(shape, p, dtype, device=None, *, counter):
    index = counter[0]
    counter[0] += 1
    size = int(np.prod(tuple(shape), dtype=np.int64))
    phase = _stable_number(f"mask-{index}") % 10
    values = (((np.arange(size) + phase) % 10) < 3).astype(np.float32)
    return torch.from_numpy(values.reshape(tuple(shape))).to(
        device=device, dtype=dtype)


def test_official_source_authentication_rejects_wrong_commit_and_dirty_tree(
        plain_tmp):
    root = Path(plain_tmp) / "official_auth"
    root.mkdir()

    def git(*args):
        return subprocess.run(
            ["git", "-C", str(root), *args], check=True,
            text=True, encoding="utf-8", stdout=subprocess.PIPE,
            stderr=subprocess.PIPE).stdout.strip()

    git("init", "-q")
    git("config", "user.name", "Quick96 Test")
    git("config", "user.email", "quick96-test@example.invalid")
    marker = root / "oracle.py"
    marker.write_text("official = True\n", encoding="utf-8")
    git("add", "oracle.py")
    git("commit", "-q", "--no-gpg-sign", "-m", "oracle source")
    local_commit = git("rev-parse", "HEAD")

    with pytest.raises(OfficialSourceAuthenticationError,
                       match="official source HEAD mismatch"):
        authenticate_official_root(root)

    authenticated = authenticate_official_root(
        root, expected_commit=local_commit)
    assert authenticated["commit"] == local_commit
    assert authenticated["tracked_state"] == "clean"

    marker.write_text("official = False\n", encoding="utf-8")
    with pytest.raises(OfficialSourceAuthenticationError,
                       match="tracked modifications"):
        authenticate_official_root(root, expected_commit=local_commit)


def test_frozen_official_tf_forward_losses_optimizer_and_checkpoints(plain_tmp,
                                                                     monkeypatch):
    fixture, metadata = _reference()
    components = _components()
    encoder, inter, decoder_src, decoder_dst = components
    _load_synthetic_components(components, metadata, plain_tmp)

    assert metadata["provenance"]["official_commit"] == (
        "14cc9d4e5ffc062856a739c8e64707654780774e")
    assert metadata["provenance"]["official_tracked_state"] == "clean"
    assert metadata["provenance"]["private_media"] is False
    assert metadata["provenance"]["pretrained_bytes"] is False
    assert metadata["determinism"] == {
        "device": "CPU",
        "environment": {
            "CUDA_VISIBLE_DEVICES": "-1",
            "OMP_NUM_THREADS": "1",
            "TF_DETERMINISTIC_OPS": "1",
            "TF_ENABLE_ONEDNN_OPTS": "0",
            "TF_NUM_INTEROP_THREADS": "1",
            "TF_NUM_INTRAOP_THREADS": "1",
        },
        "numpy_random_seeded": True,
        "python_random_seeded": True,
        "seed": 140096,
        "tensorflow_eager": False,
        "tensorflow_random_seeded": True,
    }
    assert metadata["predictor_order"] == [
        "pred_src_dst", "pred_src_dstm", "pred_dst_dstm"]
    assert [len(component.get_weights()) for component in components] == [
        8, 6, 36, 36]
    assert [component.name for component in components] == [
        "encoder", "inter", "decoder_src", "decoder_dst"]

    warped_src = torch.from_numpy(fixture["warped_src"])
    warped_dst = torch.from_numpy(fixture["warped_dst"])
    target_src = torch.from_numpy(fixture["target_src"])
    target_dst = torch.from_numpy(fixture["target_dst"])
    target_srcm = torch.from_numpy(fixture["target_srcm"])
    target_dstm = torch.from_numpy(fixture["target_dstm"])
    with torch.no_grad():
        encoder_src = encoder(warped_src)
        encoder_dst = encoder(warped_dst)
        inter_src = inter(encoder_src)
        inter_dst = inter(encoder_dst)
        src_face, src_mask = decoder_src(inter_src)
        dst_face, dst_mask = decoder_dst(inter_dst)
        swap_face, swap_mask = decoder_src(inter_dst)

    comparisons = {
        "encoder_src": encoder_src, "inter_src": inter_src,
        "decoder_src_face": src_face, "decoder_src_mask": src_mask,
        "decoder_dst_face": dst_face, "decoder_dst_mask": dst_mask,
        "ae_view_src": src_face, "ae_view_dst": dst_face,
        "ae_view_dst_mask": dst_mask, "ae_view_swap": swap_face,
        "ae_view_swap_mask": swap_mask, "ae_merge_face": swap_face,
        "ae_merge_src_mask": swap_mask, "ae_merge_dst_mask": dst_mask,
    }
    for name, actual in comparisons.items():
        _assert_parity_field(name, _np(actual), fixture[name])

    srcm_blur = nn.gaussian_blur(target_srcm, 3)
    dstm_blur = nn.gaussian_blur(target_dstm, 3)
    _assert_parity_field("src_mask_blur", _np(srcm_blur),
                         fixture["src_mask_blur"])
    _assert_parity_field("dst_mask_blur", _np(dstm_blur),
                         fixture["dst_mask_blur"])
    assert not torch.equal(srcm_blur, target_srcm)
    assert not torch.equal(dstm_blur, target_dstm)

    shell = Quick96Model.__new__(Quick96Model)
    shell.resolution = 96
    targets = {
        "target_src": target_src, "target_dst": target_dst,
        "target_srcm": target_srcm, "target_dstm": target_dstm,
        "target_srcm_blur": srcm_blur, "target_dstm_blur": dstm_blur,
    }
    predictions = {
        "pred_src_src": src_face, "pred_src_srcm": src_mask,
        "pred_dst_dst": dst_face, "pred_dst_dstm": dst_mask,
    }
    src_loss, dst_loss = shell._loss_vectors(targets, predictions)
    src_target_masked = target_src * srcm_blur
    src_pred_masked = src_face * srcm_blur
    src_dssim = torch.mean(
        10 * nn.dssim(src_target_masked, src_pred_masked,
                      max_val=1.0, filter_size=int(96 / 11.6)), dim=1)
    src_pixel_mse = torch.mean(
        10 * torch.square(src_target_masked - src_pred_masked),
        dim=(1, 2, 3))
    src_raw_mask_mse = torch.mean(
        10 * torch.square(target_srcm - src_mask), dim=(1, 2, 3))
    src_blurred_mask_mse = torch.mean(
        10 * torch.square(srcm_blur - src_mask), dim=(1, 2, 3))
    torch.testing.assert_close(
        src_loss, src_dssim + src_pixel_mse + src_raw_mask_mse)
    assert not torch.allclose(src_raw_mask_mse, src_blurred_mask_mse)
    _assert_parity_field("src_loss", _np(src_loss), fixture["src_loss"])
    _assert_parity_field("dst_loss", _np(dst_loss), fixture["dst_loss"])

    Quick96Model._bind_official_optimizer_names(components)
    trainable = sum((component.get_weights() for component in components), [])
    optimizer = nn.RMSprop(
        lr=2e-4, rho=0.9, lr_dropout=0.3, name="src_dst_opt")
    optimizer.initialize_variables(trainable, vars_on_cpu=True)
    state_names = [name for name, _ in optimizer._iter_official_weights()]
    fixture_opt = metadata["checkpoint"]["src_dst_opt.npy"]
    assert state_names == [item["key"] for item in fixture_opt]
    assert state_names[0] == "iters:0"
    assert len(state_names) == 87
    assert optimizer.iterations.dtype == torch.int64

    before = [p.detach().clone() for p in trainable[:4]]
    counter = [0]

    def parity_dropout(shape, p, dtype, device=None):
        index = counter[0]
        counter[0] += 1
        param = trainable[index]
        official_shape = tuple(
            metadata["components"]["encoder"][index]["shape"])
        size = int(np.prod(official_shape, dtype=np.int64))
        phase = _stable_number(f"mask-{index}") % 10
        official = (((np.arange(size) + phase) % 10) < 3).astype(
            np.float32).reshape(official_shape)
        internal = encoder.convert_weight_layout(official, param)
        return torch.from_numpy(np.ascontiguousarray(internal)).to(
            device=device, dtype=dtype)

    monkeypatch.setattr(
        nn, "random_binomial", parity_dropout)
    grads = [(torch.ones_like(p) * ((i + 1) * 1e-3), p)
             for i, p in enumerate(trainable[:4])]
    optimizer.get_update_op(grads)()
    after = trainable[:4]
    accumulators = optimizer._states()[:4]
    before_probes = _official_probes(encoder, before, trainable[:4])
    after_probes = _official_probes(encoder, after, trainable[:4])
    accumulator_probes = _official_probes(
        optimizer, accumulators, accumulators)
    for actual, key in (
            (before_probes, "parameter_before_probes"),
            (after_probes, "parameter_after_probes"),
            (accumulator_probes, "accumulator_probes")):
        expected = fixture[key]
        assert actual.shape == (4, 3)
        assert expected.shape == (4, 3)
        assert actual.dtype == np.float64
        assert expected.dtype == np.float64
        np.testing.assert_array_equal(actual, expected)
    assert int(optimizer.iterations) == int(fixture["optimizer_iters"])
    assert metadata["save_load_max_abs"] == 0.0
    assert metadata["resume_max_abs"] == 0.0
    resume = metadata["resume"]
    assert resume["model_count"] == 86
    assert resume["optimizer_count"] == 87
    assert resume["optimizer_iteration_name"] == "src_dst_opt/iters:0"
    assert len(resume["model"]) == 86
    assert len(resume["optimizer"]) == 87
    assert len({item["name"] for item in resume["model"]}) == 86
    assert len({item["name"] for item in resume["optimizer"]}) == 87
    for item in resume["model"] + resume["optimizer"]:
        assert item["uninterrupted_sha256"] == item["resumed_sha256"]
        assert len(item["uninterrupted_sha256"]) == 64
        assert isinstance(item["shape"], list)
        assert item["dtype"] in {"float32", "int64"}

    optimizer_path = Path(plain_tmp) / "roundtrip_src_dst_opt.npy"
    optimizer.save_weights(optimizer_path)
    optimizer_raw = pickle.loads(optimizer_path.read_bytes())
    assert list(optimizer_raw) == [item["key"] for item in fixture_opt]
    assert [list(np.asarray(value).shape)
            for value in optimizer_raw.values()] == [
                item["shape"] for item in fixture_opt]
    assert [np.asarray(value).dtype.name
            for value in optimizer_raw.values()] == [
                item["dtype"] for item in fixture_opt]

    for component in components:
        path = Path(plain_tmp) / f"roundtrip_{component.name}.npy"
        component.save_weights(path)
        raw = pickle.loads(path.read_bytes())
        expected = metadata["checkpoint"][f"{component.name}.npy"]
        assert list(raw) == [item["key"] for item in expected]
        assert [list(value.shape) for value in raw.values()] == [
            item["shape"] for item in expected]
        assert [value.dtype.name for value in raw.values()] == [
            item["dtype"] for item in expected]


def test_cpu_training_iteration_reuse_save_resume_and_strict_failure(plain_tmp,
                                                                     monkeypatch):
    root = Path(plain_tmp) / "quick96_cpu"
    model = _make_model(root)
    try:
        assert model.get_batch_size() == 4
        assert model.models_opt_on_gpu is False
        assert model.low_vram_split is False
        assert {p.device.type for p in model.src_dst_trainable_weights} == {"cpu"}
        assert len(model.src_dst_trainable_weights) == 86
        assert len(model.src_dst_opt._states()) == 86

        generated = _synthetic_batch(model, batch=1)
        samples = ((generated[0], generated[1], generated[2]),
                   (generated[3], generated[4], generated[5]))
        calls = []
        model.generate_next_samples = lambda: calls.append("fetch") or samples
        seen = []
        real_train = model.src_dst_train
        model.src_dst_train = lambda *args: seen.append(args) or (1.0, 2.0)
        # Iteration zero is divisible by three, but there is no previous batch
        # yet: it must acquire fresh samples and use the warped inputs.
        model.set_iter(0)
        assert dict(model.onTrainOneIter()) == {"src_loss": 1.0,
                                                "dst_loss": 2.0}
        assert calls == ["fetch"]
        assert seen[-1][0] is generated[0]
        assert seen[-1][3] is generated[3]

        # A later every-third iteration does have previous samples and must
        # reuse that batch while substituting its unwarped targets.
        model.set_iter(3)
        model.onTrainOneIter()
        assert calls == ["fetch"]
        assert seen[-1][0] is generated[1]
        assert seen[-1][3] is generated[4]
        model.src_dst_train = real_train

        counter = [0]
        monkeypatch.setattr(
            nn, "random_binomial",
            lambda shape, p, dtype, device=None: _controlled_dropout(
                shape, p, dtype, device, counter=counter))
        batch = _synthetic_batch(model, batch=1)
        model._src_dst_train_vectors(*batch)
        assert int(model.src_dst_opt.iterations) == 1
        model.set_iter(7)
        view_before = model.AE_view(batch[1], batch[4])
        state_before = [value.detach().clone()
                        for value in model.src_dst_opt.get_weights()]
        model.save()
        expected_files = {
            "encoder.npy", "inter.npy", "decoder_src.npy",
            "decoder_dst.npy", "src_dst_opt.npy", "data.dat"}
        assert (root / "test_Quick96_data.dat").is_file()
        assert expected_files == {
            path.name.removeprefix("test_Quick96_")
            for path in root.glob("test_Quick96_*.npy")
        } | {"data.dat"}

        counter[:] = [0]
        model._src_dst_train_vectors(*batch)
        uninterrupted = [
            _tensor_digest(value)
            for value in (model.src_dst_trainable_weights
                          + model.src_dst_opt.get_weights())]
    finally:
        model.finalize()

    resumed = _make_model(root)
    try:
        assert resumed._quick96_saved_model_resume is True
        assert resumed.get_iter() == 7
        assert int(resumed.src_dst_opt.iterations) == 1
        for actual, expected in zip(resumed.src_dst_opt.get_weights(),
                                    state_before):
            assert torch.equal(actual, expected)
        for actual, expected in zip(resumed.AE_view(batch[1], batch[4]),
                                    view_before):
            np.testing.assert_array_equal(actual, expected)
        counter[:] = [0]
        resumed._src_dst_train_vectors(*batch)
        resumed_digests = [
            _tensor_digest(value)
            for value in (resumed.src_dst_trainable_weights
                          + resumed.src_dst_opt.get_weights())]
        assert resumed_digests == uninterrupted
    finally:
        resumed.finalize()

    opt_path = root / "test_Quick96_src_dst_opt.npy"
    backup = root / "missing-opt-backup.npy"
    opt_path.replace(backup)
    try:
        with pytest.raises(FileNotFoundError, match="src_dst_opt.npy"):
            broken = _make_model(root)
            broken.finalize()
    finally:
        backup.replace(opt_path)


def test_historical_three_file_pretrained_initialization(plain_tmp):
    source_root = Path(plain_tmp) / "source"
    source = _make_model(source_root)
    try:
        source.set_iter(1)
        source.save()
        expected = {
            name: [p.detach().clone() for p in component.get_weights()]
            for name, component in (
                ("encoder.npy", source.encoder),
                ("decoder_src.npy", source.decoder_src),
                ("decoder_dst.npy", source.decoder_dst))}
    finally:
        source.finalize()

    pretrained = Path(plain_tmp) / "historical_pretrained"
    pretrained.mkdir()
    for filename in expected:
        src = source_root / f"test_Quick96_{filename}"
        dst = pretrained / filename
        try:
            os.link(src, dst)
        except OSError:
            shutil.copyfile(src, dst)
    assert {p.name for p in pretrained.iterdir()} == {
        "encoder.npy", "decoder_src.npy", "decoder_dst.npy"}

    target_root = Path(plain_tmp) / "target"
    target = _make_model(target_root, pretrained_model_path=pretrained)
    try:
        assert target._quick96_saved_model_resume is False
        assert target.pretrained_components_loaded == [
            "encoder.npy", "decoder_src.npy", "decoder_dst.npy"]
        for filename, component in (
                ("encoder.npy", target.encoder),
                ("decoder_src.npy", target.decoder_src),
                ("decoder_dst.npy", target.decoder_dst)):
            for actual, wanted in zip(component.get_weights(),
                                      expected[filename]):
                assert torch.equal(actual, wanted)
        assert int(target.src_dst_opt.iterations) == 0
        assert all(torch.count_nonzero(state) == 0
                   for state in target.src_dst_opt._states())
        assert not (pretrained / "inter.npy").exists()
        assert not (pretrained / "src_dst_opt.npy").exists()
        assert not (pretrained / "data.dat").exists()
    finally:
        target.finalize()

    corrupt_root = Path(plain_tmp) / "corrupt_target"
    corrupt = Path(plain_tmp) / "corrupt_pretrained"
    shutil.copytree(pretrained, corrupt)
    payload = pickle.loads((corrupt / "encoder.npy").read_bytes())
    first = next(iter(payload))
    payload[first] = payload[first][..., :-1]
    (corrupt / "encoder.npy").write_bytes(pickle.dumps(payload, 4))
    with pytest.raises(CheckpointLoadError):
        broken = _make_model(corrupt_root, pretrained_model_path=corrupt)
        broken.finalize()


def test_simulated_two_replica_batch_sum_mean_one_step_and_sync(plain_tmp,
                                                                monkeypatch):
    assert [Quick96Model._official_batch_layout(n) for n in range(6)] == [
        (1, 4, 4), (1, 4, 4), (2, 2, 4), (3, 1, 3),
        (4, 1, 4), (5, 1, 5)]
    model = _make_model(Path(plain_tmp) / "simulated")
    try:
        batch = _synthetic_batch(model, identical=True)
        captured = []
        real_get_update_op = model.src_dst_opt.get_update_op
        monkeypatch.setattr(
            model.src_dst_opt, "get_update_op",
            lambda gv: (lambda: captured.append(
                [gradient.detach().clone() for gradient, _ in gv])))
        model._src_dst_train_vectors(*batch)
        single = captured.pop()

        model.replica_plan.dispose()
        model.replica_plan = nn.ReplicaPlan.from_torch_devices(
            torch.device("cpu"), [torch.device("cpu"), torch.device("cpu")])
        model._quick96_tower_offset = 0
        model.tower_devices = model.replica_plan.replica_devices
        model._quick96_bs_per_tower = 2
        for component in model._quick96_components:
            model.replica_plan.add_component(component)
        model.replica_plan.initial_sync()

        shard_sizes = []
        real_forward = model._forward_tower

        def observed_forward(warped_src, warped_dst, tower,
                             include_swap=True):
            shard_sizes.append(len(warped_src))
            return real_forward(warped_src, warped_dst, tower, include_swap)

        monkeypatch.setattr(model, "_forward_tower", observed_forward)
        model._src_dst_train_vectors(*batch)
        multi = captured.pop()
        assert shard_sizes == [2, 2]
        for one, many in zip(single, multi):
            # CPU convolution kernels may accumulate a batch-of-four and two
            # batches-of-two in a slightly different order. Compare stable
            # whole-gradient norms: the factor-of-two relationship (single
            # batch sum versus the mean of two equal shard sums) is the
            # contract under test and sharply distinguishes a missing mean.
            one_norm = torch.linalg.vector_norm(one.double())
            multi_norm = torch.linalg.vector_norm((many * 2).double())
            torch.testing.assert_close(one_norm, multi_norm,
                                       rtol=2e-3, atol=2e-5)

        monkeypatch.setattr(model.src_dst_opt, "get_update_op",
                            real_get_update_op)
        counter = [0]
        monkeypatch.setattr(
            nn, "random_binomial",
            lambda shape, p, dtype, device=None: _controlled_dropout(
                shape, p, dtype, device, counter=counter))
        src_display, dst_display = model._src_dst_train_vectors(*batch)
        assert tuple(src_display.shape) == (2,)
        assert tuple(dst_display.shape) == (2,)
        assert int(model.src_dst_opt.iterations) == 1
        for component_set in model.replica_plan.components:
            for canonical, mirror in zip(component_set.canonical_params,
                                         component_set.mirror_params[1]):
                assert torch.equal(canonical, mirror)
        assert [filename for _, filename in model.get_model_filename_list()] == [
            "encoder.npy", "inter.npy", "decoder_src.npy",
            "decoder_dst.npy", "src_dst_opt.npy"]
    finally:
        model.finalize()


@pytest.mark.skipif(not torch.cuda.is_available(), reason="CUDA unavailable")
def test_cuda_and_low_vram_split_training(plain_tmp):
    nn.initialize_main_env()
    devices = Devices.getDevices()
    selected = devices[0]
    original_total_mem_gb = selected.total_mem_gb
    high = _make_model(Path(plain_tmp) / "cuda", cpu_only=False,
                       force_gpu_idxs=[selected.index], debug=False)
    try:
        assert high.models_opt_on_gpu is True
        assert high.low_vram_split is False
        assert {p.device.type for p in high.src_dst_trainable_weights} == {
            "cuda"}
        high._src_dst_train_vectors(*_synthetic_batch(high))
        assert int(high.src_dst_opt.iterations) == 1
    finally:
        high.finalize()

    try:
        selected.total_mem_gb = 3.0
        low = _make_model(Path(plain_tmp) / "low_vram", cpu_only=False,
                          force_gpu_idxs=[selected.index], debug=False)
        try:
            assert low.models_opt_on_gpu is False
            assert low.low_vram_split is True
            assert {p.device.type for p in low.src_dst_trainable_weights} == {
                "cpu"}
            assert {state.device.type for state
                    in low.src_dst_opt.get_weights()} == {"cpu"}
            assert {device.type for device in low.tower_devices} == {"cuda"}
            assert len(low.replica_plan.components) == 4
            low._src_dst_train_vectors(*_synthetic_batch(low))
            assert int(low.src_dst_opt.iterations) == 1
            for component_set in low.replica_plan.components:
                for canonical, mirror in zip(
                        component_set.canonical_params,
                        component_set.mirror_params[1]):
                    assert torch.equal(canonical, mirror.cpu())
        finally:
            low.finalize()
    finally:
        selected.total_mem_gb = original_total_mem_gb


def test_lr_dropout_fresh_masks_probability_dtype_and_device(monkeypatch):
    nn.initialize(nn.DeviceConfig.CPU(), data_format="NHWC")
    parameter = torch.nn.Parameter(torch.zeros(200_000, dtype=torch.float32))
    parameter._dfl_name = "encoder/test:0"
    optimizer = nn.RMSprop(lr=1.0, rho=0.9, lr_dropout=0.3,
                           name="src_dst_opt")
    optimizer.initialize_variables([parameter], vars_on_cpu=True)
    seen = []
    real = nn.random_binomial

    def observed(shape, p, dtype, device=None):
        mask = real(shape, p=p, dtype=dtype, device=device)
        seen.append(mask.detach().clone())
        return mask

    monkeypatch.setattr(nn, "random_binomial", observed)
    for _ in range(2):
        optimizer.get_update_op([(torch.ones_like(parameter), parameter)])()
    assert len(seen) == 2
    assert seen[0].dtype == parameter.dtype
    assert seen[0].device == parameter.device
    assert not torch.equal(seen[0], seen[1])
    for mask in seen:
        assert abs(float(mask.mean()) - 0.3) < 0.01


def test_lr_dropout_independent_parameter_masks_in_same_step(monkeypatch):
    nn.initialize(nn.DeviceConfig.CPU(), data_format="NHWC")
    parameters = [
        torch.nn.Parameter(torch.zeros(10_000, dtype=torch.float32))
        for _ in range(2)]
    for index, parameter in enumerate(parameters):
        parameter._dfl_name = f"encoder/test_{index}:0"
    optimizer = nn.RMSprop(lr=1.0, rho=0.9, lr_dropout=0.3,
                           name="src_dst_opt")
    optimizer.initialize_variables(parameters, vars_on_cpu=True)
    calls = []

    def instrumented(shape, p, dtype, device=None):
        call_index = len(calls)
        size = int(np.prod(tuple(shape), dtype=np.int64))
        values = (((np.arange(size) + call_index) % 10) < 3).astype(
            np.float32)
        mask = torch.from_numpy(values.reshape(tuple(shape))).to(
            device=device, dtype=dtype)
        calls.append({"mask": mask, "p": p, "dtype": dtype,
                      "device": device})
        return mask

    monkeypatch.setattr(nn, "random_binomial", instrumented)
    optimizer.get_update_op([
        (torch.ones_like(parameter), parameter)
        for parameter in parameters])()

    # Both calls occurred inside the one optimizer step (one iteration), and
    # the deterministic phases prove two samples rather than one shared mask.
    assert int(optimizer.iterations) == 1
    assert len(calls) == 2
    first, second = calls
    for call, parameter in zip(calls, parameters):
        assert call["p"] == 0.3
        assert call["dtype"] == parameter.dtype
        assert call["device"] == parameter.device
        assert call["mask"].dtype == parameter.dtype
        assert call["mask"].device == parameter.device
        assert float(call["mask"].mean()) == pytest.approx(0.3, abs=1e-7)
    assert first["mask"] is not second["mask"]
    assert (first["mask"].untyped_storage().data_ptr()
            != second["mask"].untyped_storage().data_ptr())
    assert not torch.equal(first["mask"], second["mask"])


def test_quick96_merge_remains_explicitly_out_of_scope():
    model = Quick96Model.__new__(Quick96Model)
    with pytest.raises(NotImplementedError, match="outside the training"):
        model.predictor_func(np.zeros((96, 96, 3), np.float32))
    with pytest.raises(NotImplementedError, match="outside the training"):
        model.get_MergerConfig()
