#!/usr/bin/env python3
"""Isolated bootstrap entry point for DeepFaceLab portable runtimes.

The Phase-13 launcher chain (plan section 19) is:

    <runtime-root>/python.exe -I -B <repo>/scripts/runtime_entry.py [app args...]

This script is the isolation boundary between a host environment and the
DeepFaceLab application. It is intentionally stdlib-only so that it runs on
the assembled standalone CPython 3.12.11 runtime without any third-party
package, and it is covered by the canonical runtime identity (its SHA-256
participates in the runtime ID).

Guarantees enforced here (in addition to the interpreter flags -I/-B):

  * PYTHONHOME / PYTHONPATH / PYTHONSTARTUP are removed from the process
    environment so no host prefix or path can leak into the app.
  * PYTHONNOUSERSITE=1 and PYTHONDONTWRITEBYTECODE=1 are set so the app
    cannot read a user site-packages or leave generated bytecode in the
    immutable runtime tree.
  * The application is executed from the repository root (the parent of this
    scripts/ directory) with sys.path pinned to that root, and never from any
    directory outside it.

Usage:
    runtime_entry.py --self-test
        Print a compact machine-readable self-test report (JSON) describing
        the interpreter that will run the app: version, implementation,
        executable, isolation flags. Exits 0 on a healthy isolated
        interpreter, 1 otherwise. Used by the runtime builder and by later
        launcher/environment checks.
    runtime_entry.py [args...]
        Run the DeepFaceLab application (main.py) with the given arguments.
"""

from __future__ import annotations

import json
import os
import runpy
import sys


SELF_TEST_MODE = "--self-test"


def _root() -> "os.PathLike[str]":
    """Repository root: the parent of this scripts/ directory."""
    return os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


def _purge_host_environment() -> None:
    for variable in ("PYTHONHOME", "PYTHONPATH", "PYTHONSTARTUP"):
        os.environ.pop(variable, None)
    os.environ["PYTHONNOUSERSITE"] = "1"
    os.environ["PYTHONDONTWRITEBYTECODE"] = "1"


def self_test_report() -> dict[str, object]:
    executable = sys.executable or ""
    healthy = bool(sys.flags.isolated) and bool(sys.dont_write_bytecode) and bool(executable)
    return {
        "dont_write_bytecode": bool(sys.dont_write_bytecode),
        "executable": executable,
        # Proves the host-environment purge happened in THIS process even
        # when the interpreter was started without -I (a hostile host can
        # otherwise inject PYTHONHOME/PYTHONPATH/PYTHONSTARTUP):
        "host_env_purged": not any(
            variable in os.environ
            for variable in ("PYTHONHOME", "PYTHONPATH", "PYTHONSTARTUP")
        ),
        "implementation": sys.implementation.name,
        "isolated": bool(sys.flags.isolated),
        "mode": "self-test",
        "ok": healthy,
        "python_version": sys.version.split()[0],
        "usersite_disabled": os.environ.get("PYTHONNOUSERSITE") == "1",
        "bytecode_disabled_env": os.environ.get("PYTHONDONTWRITEBYTECODE") == "1",
    }


def run_self_test() -> int:
    report = self_test_report()
    print(json.dumps(report, sort_keys=True))
    return 0 if report["ok"] else 1


def run_application(app_args: list[str]) -> int:
    root = _root()
    main_py = os.path.join(root, "main.py")
    if not os.path.isfile(main_py):
        print(
            "runtime-entry: application entry point 'main.py' not found next to scripts/; "
            "this runtime_entry.py does not sit inside the DeepFaceLab repository",
            file=sys.stderr,
        )
        return 1

    # Pin sys.path to the repository root: the script directory (where the
    # interpreter puts it by default) is dropped, and anything else already
    # present under -I is stdlib only and is kept.
    script_dir = os.path.dirname(os.path.abspath(__file__))
    sys.path = [
        str(root)
    ] + [entry for entry in sys.path if entry and os.path.abspath(entry) != script_dir]
    sys.argv = [main_py, *app_args]
    runpy.run_path(main_py, run_name="__main__")
    return 0


def main(argv: list[str] | None = None) -> int:
    arguments = list(sys.argv[1:]) if argv is None else list(argv)
    if not arguments:
        print("runtime-entry: no application arguments and no --self-test given", file=sys.stderr)
        return 2
    # The host environment is purged on EVERY path (self-test included) so a
    # hostile host (PYTHONHOME/PYTHONPATH/PYTHONSTARTUP, user-site state, an
    # unexpected CWD) can never reach the interpreter or the app.
    _purge_host_environment()
    sys.dont_write_bytecode = True
    if arguments[0] == SELF_TEST_MODE:
        return run_self_test()
    return run_application(arguments)


if __name__ == "__main__":
    raise SystemExit(main())
