#!/usr/bin/env python3
"""Isolated bootstrap entry point for DeepFaceLab portable runtimes.

The Phase-13 launcher chain (plan section 19) is:

    <runtime-root>/python.exe -I -B <repo>/scripts/runtime_entry.py [app args...]

This script is the isolation boundary between a host environment and the
DeepFaceLab application. It is intentionally stdlib-only so that it runs on
the assembled standalone CPython 3.12.11 runtime without any third-party
package, and it is covered by the canonical runtime identity (its SHA-256
participates in the runtime ID).

Guarantees enforced here (in addition to the interpreter flags -I/-B):

  * PYTHONHOME / PYTHONPATH / PYTHONSTARTUP are removed from the process
    environment so no host prefix or path can leak into the app.
  * PYTHONNOUSERSITE=1 and PYTHONDONTWRITEBYTECODE=1 are set so the app
    cannot read a user site-packages or leave generated bytecode in the
    immutable runtime tree.
  * Stale CUDA toolkit state is sanitized here (the authoritative owner per
    the Phase-13 launcher-layer split; the launcher itself adds no CUDA
    mask). Exact policy, applied before any application import:
      1. capture variable names/status (never sensitive values);
      2. clear CUDA_PATH, CUDA_HOME and CUDA_VISIBLE_DEVICES
         (case-insensitive name matching  -  Windows semantics);
      3. remove from the CHILD PATH only:
         a. <root>\\bin and <root>\\lib\\x64 of each pre-removal
            CUDA_PATH / CUDA_HOME toolkit root (no other descendant of a
            root  -  docs, extras, ...  -  is ever removed);
         b. canonical NVIDIA toolkit bin entries
            ...\\NVIDIA GPU Computing Toolkit\\CUDA\\v*\\bin
            (case-insensitive), even when neither CUDA_PATH nor
            CUDA_HOME is set;
      4. preserve ALL other PATH entries. No broad "contains cuda"
         substring deletion is ever performed and no CUDA-like entry is
         claimed safe by name. Only this process's environment is
         affected; the parent process and the system PATH are never
         modified. This is NOT a claim of complete immunity from
         arbitrary DLL collisions: a toolkit whose bin directory is
         neither declared via CUDA_PATH/CUDA_HOME nor matches the
         canonical NVIDIA pattern can still supply colliding DLLs.
  * The application is executed from the repository root (the parent of this
    scripts/ directory) with sys.path pinned to that root, and never from any
    directory outside it.

Usage:
    runtime_entry.py --self-test
        Print a compact machine-readable self-test report (JSON) describing
        the interpreter that will run the app: version, implementation,
        executable, isolation flags. Exits 0 on a healthy isolated
        interpreter, 1 otherwise. Used by the runtime builder and by later
        launcher/environment checks.
    runtime_entry.py [args...]
        Run the DeepFaceLab application (main.py) with the given arguments.
"""

from __future__ import annotations

import json
import os
import re
import runpy
import sys


SELF_TEST_MODE = "--self-test"


def _root() -> "os.PathLike[str]":
    """Repository root: the parent of this scripts/ directory."""
    return os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


def _purge_host_environment() -> None:
    for variable in ("PYTHONHOME", "PYTHONPATH", "PYTHONSTARTUP"):
        os.environ.pop(variable, None)
    os.environ["PYTHONNOUSERSITE"] = "1"
    os.environ["PYTHONDONTWRITEBYTECODE"] = "1"


#: CUDA variables removed from the child environment (case-insensitive on
#: Windows, where both the OS environment and os.environ match names
#: regardless of case; the explicit case-insensitive scan below makes the
#: behaviour identical for plain test dictionaries).
CUDA_ENVIRONMENT_VARIABLES = ("CUDA_PATH", "CUDA_HOME", "CUDA_VISIBLE_DEVICES")

#: Variables whose VALUES declare the roots of a stale CUDA toolkit
#: install. From each declared root ONLY the two approved derived
#: locations are removed from the child PATH: ``<root>\bin`` and
#: ``<root>\lib\x64`` (compared case-insensitively per Windows path
#: semantics). Every other location under the root  -  the root itself,
#: docs, extras, anything else  -  is preserved.
CUDA_TOOLKIT_ROOT_VARIABLES = ("CUDA_PATH", "CUDA_HOME")
CUDA_TOOLKIT_DERIVED_DIRS = (("bin",), ("lib", "x64"))

#: Canonical NVIDIA toolkit bin directories are pruned even when neither
#: CUDA_PATH nor CUDA_HOME is set:
#:   ...<anything>\NVIDIA GPU Computing Toolkit\CUDA\v<version>\bin
#: matched case-insensitively (Windows path semantics); both backslash and
#: forward slash separators are recognised.
CANONICAL_NVIDIA_TOOLKIT_BIN_RE = re.compile(
    r"nvidia gpu computing toolkit[\\/]cuda[\\/]v[^\\/]+[\\/]bin$",
    re.IGNORECASE,
)


def _ci_lookup(environ, name: str) -> "str | None":
    """Case-insensitive environment lookup.

    On Windows ``os.environ`` is already case-insensitive, so the direct
    access wins; the explicit scan keeps the helper exact for plain ``dict``
    inputs (used by the test suite on any platform).
    """
    try:
        return environ[name]
    except (KeyError, TypeError):
        pass
    target = name.casefold()
    for key in environ:
        if str(key).casefold() == target:
            return environ[key]
    return None


def _ci_remove(environ, name: str) -> None:
    try:
        del environ[name]
    except (KeyError, TypeError):
        pass
    target = name.casefold()
    for key in list(environ):
        if str(key).casefold() == target:
            del environ[key]
            return


def sanitize_cuda_environment(
    environ: "dict[str, str] | os._Environ[str]" = os.environ,
) -> dict[str, object]:
    """Remove stale CUDA toolkit state from the given environment mapping.

    Exact policy (authoritative; see the module docstring):

    1. capture the variable names/status (never sensitive values);
    2. clear ``CUDA_PATH``, ``CUDA_HOME`` and ``CUDA_VISIBLE_DEVICES``
       (variable names matched case-insensitively - Windows semantics);
    3. remove from the CHILD PATH only:
       a. each pre-removal ``CUDA_PATH``/``CUDA_HOME`` toolkit root's
          ``<root>\\bin``;
       b. each pre-removal ``CUDA_PATH``/``CUDA_HOME`` toolkit root's
          ``<root>\\lib\\x64``;
       c. canonical NVIDIA toolkit bin entries
          ``...\\NVIDIA GPU Computing Toolkit\\CUDA\\v*\\bin``
          (case-insensitive), even when both variables are absent;
    4. preserve ALL other PATH entries - in particular ``<root>\\docs``,
       ``<root>\\extras`` and every other descendant of a declared toolkit
       root; no broad "contains cuda" substring deletion is ever
       performed and no CUDA-like entry is claimed safe by name.

    Only the given environment mapping (the child process environment) is
    modified; the parent process and the system PATH are never touched.

    Returns a report dictionary (``cleared`` variable names as they were
    spelled, ``declared_roots`` the approved derived locations captured
    from pre-removal ``CUDA_PATH``/``CUDA_HOME`` values, and
    ``pruned_path_entries`` the exact PATH entries removed).
    """
    declared_roots: "set[str]" = set()
    for variable in CUDA_TOOLKIT_ROOT_VARIABLES:
        value = _ci_lookup(environ, variable)
        if value:
            root = os.path.normcase(os.path.normpath(value))
            for parts in CUDA_TOOLKIT_DERIVED_DIRS:
                declared_roots.add(os.path.normcase(os.path.normpath(os.path.join(root, *parts))))
    cleared: list[str] = []
    for variable in CUDA_ENVIRONMENT_VARIABLES:
        for key in list(environ):
            if str(key).casefold() == variable.casefold():
                cleared.append(str(key))
                del environ[key]
    pruned: list[str] = []
    path_value = _ci_lookup(environ, "PATH")
    if path_value:
        kept: list[str] = []
        for part in path_value.split(os.pathsep):
            if not part:
                kept.append(part)
                continue
            candidates = (part, os.path.normpath(part))
            if any(os.path.normcase(candidate) in declared_roots for candidate in candidates) or any(
                CANONICAL_NVIDIA_TOOLKIT_BIN_RE.search(candidate) for candidate in candidates
            ):
                pruned.append(part)
            else:
                kept.append(part)
        if pruned:
            environ["PATH"] = os.pathsep.join(kept)
    return {
        "cleared": cleared,
        "declared_roots": sorted(declared_roots),
        "pruned_path_entries": pruned,
    }


def self_test_report(cuda_sanitization: dict[str, object] | None = None) -> dict[str, object]:
    executable = sys.executable or ""
    healthy = bool(sys.flags.isolated) and bool(sys.dont_write_bytecode) and bool(executable)
    report: dict[str, object] = {
        "dont_write_bytecode": bool(sys.dont_write_bytecode),
        "executable": executable,
        # Proves the host-environment purge happened in THIS process even
        # when the interpreter was started without -I (a hostile host can
        # otherwise inject PYTHONHOME/PYTHONPATH/PYTHONSTARTUP):
        "host_env_purged": not any(
            _ci_lookup(os.environ, variable) is not None
            for variable in ("PYTHONHOME", "PYTHONPATH", "PYTHONSTARTUP")
        ),
        "implementation": sys.implementation.name,
        "isolated": bool(sys.flags.isolated),
        "mode": "self-test",
        "ok": healthy,
        "python_version": sys.version.split()[0],
        "usersite_disabled": os.environ.get("PYTHONNOUSERSITE") == "1",
        "bytecode_disabled_env": os.environ.get("PYTHONDONTWRITEBYTECODE") == "1",
        # CUDA sanitation report (authoritative owner of CUDA state, per the
        # Phase-13 launcher-layer split): what was cleared from this
        # process's environment and which PATH entries were pruned.
        "cuda_sanitized": cuda_sanitization is not None,
        "cuda_cleared_variables": sorted(
            str(name) for name in (cuda_sanitization or {}).get("cleared", ())
        ),
        "cuda_pruned_path_entries": list(
            (cuda_sanitization or {}).get("pruned_path_entries", ())
        ),
    }
    return report


def run_self_test(cuda_sanitization: dict[str, object] | None = None) -> int:
    report = self_test_report(cuda_sanitization)
    print(json.dumps(report, sort_keys=True))
    return 0 if report["ok"] else 1


def run_application(app_args: list[str]) -> int:
    root = _root()
    main_py = os.path.join(root, "main.py")
    if not os.path.isfile(main_py):
        print(
            "runtime-entry: application entry point 'main.py' not found next to scripts/; "
            "this runtime_entry.py does not sit inside the DeepFaceLab repository",
            file=sys.stderr,
        )
        return 1

    # Pin sys.path to the repository root: the script directory (where the
    # interpreter puts it by default) is dropped, and anything else already
    # present under -I is stdlib only and is kept.
    script_dir = os.path.dirname(os.path.abspath(__file__))
    sys.path = [
        str(root)
    ] + [entry for entry in sys.path if entry and os.path.abspath(entry) != script_dir]
    sys.argv = [main_py, *app_args]
    runpy.run_path(main_py, run_name="__main__")
    return 0


def main(argv: list[str] | None = None) -> int:
    arguments = list(sys.argv[1:]) if argv is None else list(argv)
    if not arguments:
        print("runtime-entry: no application arguments and no --self-test given", file=sys.stderr)
        return 2
    # The host environment is purged on EVERY path (self-test included) so a
    # hostile host (PYTHONHOME/PYTHONPATH/PYTHONSTARTUP, user-site state, an
    # unexpected CWD) can never reach the interpreter or the app.
    _purge_host_environment()
    # CUDA toolkit sanitation (authoritative owner: this bootstrap, not the
    # launcher) runs before any application import on every path.
    cuda_sanitization = sanitize_cuda_environment(os.environ)
    sys.dont_write_bytecode = True
    if arguments[0] == SELF_TEST_MODE:
        return run_self_test(cuda_sanitization)
    return run_application(arguments)


if __name__ == "__main__":
    raise SystemExit(main())
